apiVersion: batch/v1
kind: Job
metadata:
  name: dice
spec:
  template:
    spec:
      containers:
      - name: dice
        image: dice
        command: ["6",  "2"]
      restartPolicy: Never
  backoffLimit: 4
