apiVersion: batch/v1
kind: Job
metadata:
  name: dice
spec:
  template:
    spec:
      containers:
      - name: dice
        image: docker-registry.default.svc:5000/dice/dice
        command: ["/opt/dice", "2",  "6"]
      restartPolicy: Never
  backoffLimit: 4
